version: "3.8"

services:
  cvbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cvbuilder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
